### ISSUE TITLE
akka-http-session can not be co-used with akka-cluster

### ISSUE THREAD

**Issue by epiphyllum** [softwaremill/akka-http-session#24]
it can be always replayed  when libraryDepenencies has akka-cluster and akka-http-session

Exception in thread "main" java.lang.NoSuchMethodError: akka.actor.LocalActorRefProvider.log()Lakka/event/LoggingAdapter

**Comment by adamw** [comment]
Which version of akka, akka-cluster & akka-http-session?

**Comment by epiphyllum** [comment]
akka 2.4.11 with   akka-http-session 0.3.0

**Comment by adamw** [comment]
akka-http-session through akka-http version 10 has a transitive dependency to `akka-actor 2.4.14`. Maybe that causes `akka-actor` to be bumped to `2.4.14`, but `akka-cluster` stays at `2.4.11`, causing the inconsistency?

**Comment by epiphyllum** [comment]
when I upgrade all the akka-xxx to 2.4.16  akka-http to 10.0.1  
all is ok
